#This script will clean the data

def data_clean(Players18):
    #First bit will clean the 2018/2019 season data
    Players18['name'] = Players18['name'].astype(str).str[:-3] #Removing the last 3 digits from player name.
    Players18 = Players18.replace({'_':' '}, regex=True) #Removing the _ from player name.
    Players18 = Players18.replace({'�':'symb'}, regex=True) #Getting rid of the symbol and replace with unique identifier
    Players18 = Players18.replace({' ':''}, regex=True) #Removing spaces for ease.
    
    ## This next bit takes the platers names with symbols in and corrects thier names.
    Players18 = Players18.replace({'symbaglar Ssymbysymbncsymb':'CaglarSöyüncü'}, regex=True)
    Players18 = Players18.replace({'symblvaroMorata':'ÁlvaroMorata'}, regex=True)
    Players18 = Players18.replace({'AdalbertoPesymbaranda':'AdalbertoPeñaranda'}, regex=True)
    Players18 = Players18.replace({'AdamaTraorsymb':'AdamaTraoré'}, regex=True)
    Players18 = Players18.replace({'AdrisymbnSanMigueldelCastillo':'Adrián'}, regex=True)
    Players18 = Players18.replace({'AlexanderSsymbrloth':'AlexanderSørloth'}, regex=True)
    Players18 = Players18.replace({'AlexisSsymbnchez':'AlexisSánchez'}, regex=True)
    Players18 = Players18.replace({'Andrsymb-FrankZamboAnguissa':'André-FrankZamboAnguissa'}, regex=True)
    Players18 = Players18.replace({'AndrsymbFilipeTavaresGomes':'AndréGomes'}, regex=True)
    Players18 = Players18.replace({'AndrsymbSchsymbrrle':'AndréSchürrle'}, regex=True)
    Players18 = Players18.replace({'AntonioRsymbdiger':'AntonioRüdiger'}, regex=True)
    Players18 = Players18.replace({'AyozePsymbrez':'AyozePérez'}, regex=True)
    Players18 = Players18.replace({'BernardAnsymbcioCaldeiraDuarte':'Bernard'}, regex=True)
    Players18 = Players18.replace({'CsymbdricSoares':'CédricSoares'}, regex=True)
    Players18 = Players18.replace({'CsymbsarAzpilicueta':'CésarAzpilicueta'}, regex=True)
    Players18 = Players18.replace({'CaglarSsymbysymbncsymb':'CaglarSöyüncü'}, regex=True)
    Players18 = Players18.replace({'CarlosSsymbnchez':''}, regex=True)
    Players18 = Players18.replace({'CescFsymbbregas':'CescFàbregas'}, regex=True)
    Players18 = Players18.replace({'CheikhouKouyatsymb':'CheikhouKouyaté'}, regex=True)
    Players18 = Players18.replace({'ChrisLsymbwe':'ChrisLöwe'}, regex=True)
    Players18 = Players18.replace({'DavinsonSsymbnchez':'DavinsonSánchez'}, regex=True)
    Players18 = Players18.replace({'DavyPrsymbpper':'DavyPröpper'}, regex=True)
    Players18 = Players18.replace({'DenisSusymbrez':'DenisSuarez'}, regex=True)
    Players18 = Players18.replace({'EmilianoMartsymbnez':'EmilianoMartínez'}, regex=True)
    Players18 = Players18.replace({'FabisymbnBalbuena':'FabiánBalbuena'}, regex=True)
    Players18 = Players18.replace({'FabianSchsymbr':'FabianSchär'}, regex=True)
    Players18 = Players18.replace({'FabricioAgostoRamsymbrez':'Fabricio Agosto'}, regex=True)
    Players18 = Players18.replace({'FedericoFernsymbndez':'FedericoFernández'}, regex=True)
    Players18 = Players18.replace({'FloydAyitsymb':'FloydAyité'}, regex=True)
    Players18 = Players18.replace({'FousseniDiabatsymb':'FousseniDiabaté'}, regex=True)
    Players18 = Players18.replace({'FranciscoFemensymbaFar ':'KikoFemenía'}, regex=True)
    Players18 = Players18.replace({'GasymbtanBong':'GaëtanBong'}, regex=True)
    Players18 = Players18.replace({'Georges-KsymbvinNkoudou':'Georges-KévinNkoudou'}, regex=True)
    Players18 = Players18.replace({'GonzaloHiguasymbn':'GonzaloHiguain'}, regex=True)
    Players18 = Players18.replace({'HsymbctorBellersymb':'HéctorBellerín'}, regex=True)
    Players18 = Players18.replace({'HsymblderCosta':'HélderCosta'}, regex=True)
    Players18 = Players18.replace({'HsymbvardNordtveit':'HåvardNordtveit'}, regex=True)
    Players18 = Players18.replace({'IbrahimaCisssymb':'IbrahimaCissé'}, regex=True)
    Players18 = Players18.replace({'IlkayGsymbndogan':'IlkayGündogan'}, regex=True)
    Players18 = Players18.replace({'JsymbrgenLocadia':'JürgenLocadia'}, regex=True)
    Players18 = Players18.replace({'JavierHernsymbndezBalcsymbzar':'JavierHernandez'}, regex=True)
    Players18 = Players18.replace({'JosymboFilipeIriaSantosMoutinho':'JoãoMoutinho'}, regex=True)
    Players18 = Players18.replace({'JonasLsymbssl':'JonasLössl'}, regex=True)
    Players18 = Players18.replace({'JossymbDiogoDalotTeixeira':'DiogoDalot'}, regex=True)
    Players18 = Players18.replace({'JossymbHeribertoIzquierdoMena':'JoséIzquierdo'}, regex=True)
    Players18 = Players18.replace({'JossymbHolebas':'JoséHolebas'}, regex=True)
    Players18 = Players18.replace({'JoseLuisMatoSanmartsymbn':'NA'}, regex=True)
    Players18 = Players18.replace({'LeroySansymb':'LeroySané'}, regex=True)
    Players18 = Players18.replace({'LosymbcDamour':'LoïcDamour'}, regex=True)
    Players18 = Players18.replace({'LucasPsymbrez':'LucasPérez'}, regex=True)
    Players18 = Players18.replace({'MartsymbnMontoya':'MartínMontoya'}, regex=True)
    Players18 = Players18.replace({'Mesutsymbzil':'MesutÖzil'}, regex=True)
    Players18 = Players18.replace({'MiguelAlmirsymbn':'MiguelAlmiron'}, regex=True)
    Players18 = Players18.replace({'MohamedDiamsymb':'MohamedDiamé'}, regex=True)
    Players18 = Players18.replace({'MousaDembsymblsymb':'MousaDembélé'}, regex=True)
    Players18 = Players18.replace({'N\'GoloKantsymb':'N\'GoloKanté'}, regex=True)
    Players18 = Players18.replace({'NathanAksymb':'NathanAké'}, regex=True)
    Players18 = Players18.replace({'NicolsymbsOtamendi':'NicolásOtamendi'}, regex=True)
    Players18 = Players18.replace({'PapeSouarsymb':'PapeSouaré'}, regex=True)
    Players18 = Players18.replace({'PascalGrosymb':'PascalGroß'}, regex=True)
    Players18 = Players18.replace({'PedroRodrsymbguezLedesma':'Pedro'}, regex=True)
    Players18 = Players18.replace({'Pierre-EmileHsymbjbjerg':'Pierre-EmileHøjbjerg'}, regex=True)
    Players18 = Players18.replace({'RsymbbenDiogodaSilvaNeves':'RúbenNeves'}, regex=True)
    Players18 = Players18.replace({'RsymbbenGonsymbaloSilvaNascimentoVinagre ':'RúbenVinagre'}, regex=True)
    Players18 = Players18.replace({'RasymblJimsymbnez':'RaúlJiménez'}, regex=True)
    Players18 = Players18.replace({'RoderickJeffersonGonsymbalvesMiranda':'RoderickMiranda'}, regex=True)
    Players18 = Players18.replace({'RomainSasymbss':'RomainSaïss'}, regex=True)
    Players18 = Players18.replace({'RuiPedrodosSantosPatrsymbcio':'RuiPatrício'}, regex=True)
    Players18 = Players18.replace({'SadioMansymb':'SadioMané'}, regex=True)
    Players18 = Players18.replace({'SalomsymbnRondsymbn':'SalomónRondón'}, regex=True)
    Players18 = Players18.replace({'SandroRamsymbrez':'SandroRamírez'}, regex=True)
    Players18 = Players18.replace({'SebastianPrsymbdl':'SebastianPrödl'}, regex=True)
    Players18 = Players18.replace({'SergioAgsymbero':'SergioAgüero'}, regex=True)
    Players18 = Players18.replace({'TiemousymbBakayoko':'TiemouéBakayoko'}, regex=True)
    Players18 = Players18.replace({'symbctorCamarasa':'VíctorCamarasa'}, regex=True)
    Players18 = Players18.replace({'VictorLindelsymbf':'VictorLindelöf'}, regex=True)
    Players18 = Players18.replace({'symbaglarSsymbysymbncsymb':'CaglarSöyüncü'}, regex=True)
    Players18 = Players18.replace({'AlissonRamsesBecker':'Alisson'}, regex=True)
    Players18 = Players18.replace({'BamideleAlli':'DeleAlli'}, regex=True)
    Players18 = Players18.replace({'BenjaminChilwell':'BenChilwell'}, regex=True)
    Players18 = Players18.replace({'BernardoFernandesdaSilvaJunior':'Bernardo'}, regex=True)
    Players18 = Players18.replace({'BernardoMotaVeigadeCarvalhoeSilva':'BernardoSilva'}, regex=True)
    Players18 = Players18.replace({'BerndLen':'BerndLeno'}, regex=True)
    Players18 = Players18.replace({'BrunoSaltorGrau':'Bruno'}, regex=True)
    Players18 = Players18.replace({'CalumChamber':'CalumChambers'}, regex=True)
    Players18 = Players18.replace({'DaniloLuizdaSilva':'Danilo'}, regex=True)
    Players18 = Players18.replace({'DavidLuizMoreiraMarinho':'DavidLuiz'}, regex=True)
    Players18 = Players18.replace({'EdersonSantanadeMoraes':'Ederson'}, regex=True)
    Players18 = Players18.replace({'EmersonPalmieridosSantos':'Emerson'}, regex=True)
    Players18 = Players18.replace({'FabioHenriqueTavares':'Fabinho'}, regex=True)
    Players18 = Players18.replace({'FelipeAndersonPereiraGomes':'FelipeAnderson'}, regex=True)
    Players18 = Players18.replace({'FernandoLuizRosa':'Fernandinho'}, regex=True)
    Players18 = Players18.replace({'FranciscoFemensymbaFar':'KikoFemenía'}, regex=True)
    Players18 = Players18.replace({'FredericoRodriguesdePaulaSantos':'Fred'}, regex=True)
    Players18 = Players18.replace({'GabrielFernandodeJesus':'GabrielJesus'}, regex=True)
    Players18 = Players18.replace({'Heung-MinSon':'SonHeung-Min'}, regex=True)
    Players18 = Players18.replace({'IsaacSuccessAjayi':'IsaacSuccess'}, regex=True)
    Players18 = Players18.replace({'JonathanCastroOtto':'Jonny'}, regex=True)
    Players18 = Players18.replace({'JorgeLuizFrelloFilho':'Jorginho'}, regex=True)
    Players18 = Players18.replace({'LaurentKoscieln':'LaurentKoscielny'}, regex=True)
    Players18 = Players18.replace({'LucasRodriguesMouradaSilva':'LucasMoura'}, regex=True)
    Players18 = Players18.replace({'MathewRyan':'MatRyan'}, regex=True)
    Players18 = Players18.replace({'NachoMonrea':'NachoMonreal'}, regex=True)
    Players18 = Players18.replace({'PetrCec':'PetrCech'}, regex=True)
    Players18 = Players18.replace({'RsymbbenGonsymbaloSilvaNascimentoVinagre':'RúbenVinagre'}, regex=True)
    Players18 = Players18.replace({'RicardoDomingosBarbosaPereira':'RicardoPereira'}, regex=True)
    Players18 = Players18.replace({'RicharlisondeAndrade':'Richarlison'}, regex=True)
    Players18 = Players18.replace({'RobHoldin':'RobHolding'}, regex=True)
    Players18 = Players18.replace({'SeadKolasina':'SeadKolasinac'}, regex=True)
    Players18 = Players18.replace({'ShkodranMustaf':'ShkodranMustafi'}, regex=True)
    Players18 = Players18.replace({'SokratisPapastathopoulos':'Sokratis'}, regex=True)
    Players18 = Players18.replace({'SolomonMarch':'SollyMarch'}, regex=True)
    Players18 = Players18.replace({'Sung-yuengKi':'KiSung-yueng'}, regex=True)
    Players18 = Players18.replace({'VVíctorCamarasa':'VíctorCamarasa'}, regex=True)
    Players18 = Players18.replace({'WillianBorgesDaSilva':'Willian'}, regex=True)

    ## Removing Players that played 0 minutes
    Players18 = Players18[Players18.minutes != 0]
    return Players18

